apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: e5555z4k7-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/e5555z4k7-java-quarkus-gitops